from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from io import BytesIO
import datetime
import os


# =========================================================
# LOGO PRELOAD
# =========================================================

BENTONG_LOGO = None
BENTONG_LOGO_PATH = "app/resources/images/majlisbentong.png"

COMPANY_LOGO = None
COMPANY_LOGO_PATH = "app/resources/images/jip_logo.png"


try:
    if os.path.exists(BENTONG_LOGO_PATH):
        with open(BENTONG_LOGO_PATH, "rb") as f:
            BENTONG_LOGO = ImageReader(BytesIO(f.read()))
        print("[INFO] Bentong logo preloaded successfully.")
    else:
        print(f"[WARN] Bentong logo not found at: {BENTONG_LOGO_PATH}")
except Exception as e:
    print(f"[WARN] Failed to load Bentong logo: {e}")


try:
    if os.path.exists(COMPANY_LOGO_PATH):
        with open(COMPANY_LOGO_PATH, "rb") as f:
            COMPANY_LOGO = ImageReader(BytesIO(f.read()))
        print("[INFO] Company logo preloaded successfully.")
    else:
        print(f"[WARN] Company logo not found at: {COMPANY_LOGO_PATH}")
except Exception as e:
    print(f"[WARN] Failed to load company logo: {e}")


# =========================================================
# HELPERS
# =========================================================

def _format_money(value):
    try:
        return f"{float(value):,.2f}"
    except Exception:
        return "0.00"


def _safe_text(value):
    value = str(value or "").strip()
    return value if value else "-"


def _format_date(value):
    if not value:
        return "-"

    try:
        if isinstance(value, datetime.datetime):
            return value.strftime("%d %b %Y")
        if isinstance(value, datetime.date):
            return value.strftime("%d %b %Y")

        dt = datetime.datetime.strptime(str(value), "%Y-%m-%d")
        return dt.strftime("%d %b %Y")
    except Exception:
        return str(value)


def _build_address(*parts):
    cleaned = []
    for part in parts:
        part = str(part or "").strip()
        if part:
            cleaned.append(part)
    return ", ".join(cleaned) if cleaned else "-"


def _wrap_text_lines(c, text, max_width, font_name="Helvetica", font_size=9):
    words = str(text or "-").split()
    lines = []
    line = ""

    for word in words:
        test_line = f"{line} {word}".strip()
        if c.stringWidth(test_line, font_name, font_size) <= max_width:
            line = test_line
        else:
            if line:
                lines.append(line)
            line = word

    if line:
        lines.append(line)

    return lines if lines else ["-"]


def _draw_image_keep_ratio(c, img, x, y, max_width, max_height):
    try:
        img_width, img_height = img.getSize()
        ratio = min(max_width / img_width, max_height / img_height)
        draw_width = img_width * ratio
        draw_height = img_height * ratio

        c.drawImage(
            img,
            x,
            y + (max_height - draw_height) / 2,
            width=draw_width,
            height=draw_height,
            mask="auto",
        )
    except Exception as e:
        print(f"[WARN] Failed to draw image: {e}")


def _draw_page_header(c, width, height, primary_blue, secondary_blue, light_blue):
    header_height = 155

    c.setFillColor(primary_blue)
    c.rect(0, height - header_height, width, header_height, fill=True, stroke=False)

    c.setFillColor(secondary_blue)
    c.rect(0, height - 38, width, 38, fill=True, stroke=False)

    c.setFillColor(light_blue)
    c.rect(0, height - 12, width, 12, fill=True, stroke=False)

    c.setFillColor(colors.HexColor("#002B6B"))
    c.rect(0, height - header_height, width, 38, fill=True, stroke=False)

    if BENTONG_LOGO:
        _draw_image_keep_ratio(c, BENTONG_LOGO, 35, height - 122, 85, 85)

    if COMPANY_LOGO:
        _draw_image_keep_ratio(c, COMPANY_LOGO, width - 160, height - 112, 120, 70)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, height - 52, "MAJLIS PERBANDARAN BENTONG")

    c.setFont("Helvetica", 9)
    c.drawCentredString(
        width / 2,
        height - 70,
        "Jalan Ketari, 28700 Bentong, Pahang Darul Makmur",
    )

    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(width / 2, height - 91, "RENTAL PAYMENT RECEIPT")

    c.setFont("Helvetica", 8)
    c.drawCentredString(width / 2, height - 108, "Generated by TIP Bentong")


def _draw_footer(c, width, primary_blue, grey_text):
    c.setStrokeColor(colors.HexColor("#D9E8FF"))
    c.line(45, 82, width - 45, 82)

    if BENTONG_LOGO:
        _draw_image_keep_ratio(c, BENTONG_LOGO, 50, 25, 35, 35)

    if COMPANY_LOGO:
        _draw_image_keep_ratio(c, COMPANY_LOGO, width - 70, 25, 55, 35)

    c.setFillColor(primary_blue)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(width / 2, 62, "Majlis Perbandaran Bentong")

    c.setFillColor(grey_text)
    c.setFont("Helvetica", 8)
    c.drawCentredString(width / 2, 48, "Jalan Ketari, 28700 Bentong, Pahang Darul Makmur")
    c.drawCentredString(width / 2, 34, "Telephone : 04-5497555 | Application : TIP Bentong")


def _draw_table_header(c, y, table_left, table_right, table_width, secondary_blue):
    c.setFillColor(secondary_blue)
    c.roundRect(table_left, y, table_width, 36, 12, fill=True, stroke=False)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(table_left + 18, y + 12, "#")
    c.drawString(table_left + 55, y + 12, "Sewaan Details")
    c.drawRightString(table_right - 18, y + 12, "Amount Paid")


# =========================================================
# NORMALIZE API DATA
# =========================================================

def build_sewaan_receipt_item_from_api(data):
    return {
        "account_number": data.get("account_no", "-"),
        "old_account_number": data.get("old_account_no", "-"),
        "tenant_name": data.get("name", "-"),
        "registration_no": data.get("rent_pdaftaran", "-"),
        "start_date": data.get("start_date", "-"),
        "end_date": data.get("end_date", "-"),
        "premise_address": _build_address(
            data.get("rent_alamatswn"),
            data.get("rent_jalanname"),
            data.get("rent_postcode"),
            data.get("rent_bandarnam"),
            data.get("rent_negeri"),
        ),
        "mailing_address": _build_address(
            data.get("alamat1"),
            data.get("alamat2"),
            data.get("alamat3"),
            data.get("alamat4"),
            data.get("postcode"),
            data.get("pekan_name"),
            data.get("ten_negeri"),
        ),
        "outstanding_rent": data.get("tunggakan_sewa", "0"),
        "current_rent": data.get("rental_fee", "0"),
        "water_charge": data.get("tunggakan_caj_air", "0"),
        "electric_charge": data.get("tunggakan_caj_elektrik", "0"),
        "management_charge": data.get("tunggakan_caj_pengurusan", "0"),
        "amount": data.get("jumlah", "0"),
    }


# =========================================================
# SEWAAN RECEIPT GENERATOR - PBT BENTONG
# =========================================================

def generate_sewaan_receipt_bentong(
    paid_date: datetime.datetime,
    payment_method: str,
    sewaan_items: list = None,
    order_no: str = None,
    bank_trx_no: str = None,
):
    if sewaan_items is None:
        sewaan_items = []

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    primary_blue = colors.HexColor("#003B8E")
    secondary_blue = colors.HexColor("#0057D9")
    light_blue = colors.HexColor("#0A84FF")
    soft_blue = colors.HexColor("#EDF4FF")
    grey_text = colors.HexColor("#666666")
    dark_text = colors.HexColor("#222222")

    table_left = 45
    table_right = width - 45
    table_width = table_right - table_left

    footer_safe_y = 115
    item_gap = 10
    total_gap = 24

    _draw_page_header(c, width, height, primary_blue, secondary_blue, light_blue)

    y = height - 205

    c.setFillColor(primary_blue)
    c.setFont("Helvetica-Bold", 28)
    c.drawString(45, y, "Receipt")

    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(secondary_blue)
    c.drawString(155, y + 5, f"#{order_no or '-'}")

    c.setFont("Helvetica", 10)
    c.setFillColor(grey_text)
    c.drawString(45, y - 24, f"Paid at {paid_date.strftime('%d %b %Y %I:%M %p')}")
    c.drawString(45, y - 40, f"Payment Method: {_safe_text(payment_method)}")

    if bank_trx_no:
        c.drawString(45, y - 56, f"Bank Transaction No: {bank_trx_no}")

    y -= 112
    _draw_table_header(c, y, table_left, table_right, table_width, secondary_blue)
    y -= 42

    total_amount = 0.0

    for index, item in enumerate(sewaan_items, start=1):
        account_number = _safe_text(item.get("account_number"))
        old_account_number = _safe_text(item.get("old_account_number"))
        tenant_name = _safe_text(item.get("tenant_name"))
        registration_no = _safe_text(item.get("registration_no"))

        start_date = _format_date(item.get("start_date"))
        end_date = _format_date(item.get("end_date"))

        premise_address = _safe_text(item.get("premise_address"))
        mailing_address = _safe_text(item.get("mailing_address"))

        outstanding_rent = item.get("outstanding_rent", "0")
        current_rent = item.get("current_rent", "0")
        water_charge = item.get("water_charge", "0")
        electric_charge = item.get("electric_charge", "0")
        management_charge = item.get("management_charge", "0")

        amount = float(item.get("amount", 0) or 0)
        total_amount += amount

        premise_lines = _wrap_text_lines(c, premise_address, 305, "Helvetica", 9)
        mailing_lines = _wrap_text_lines(c, mailing_address, 305, "Helvetica", 9)

        row_height = 185 + (len(premise_lines) * 11) + (len(mailing_lines) * 11)

        if y - row_height < footer_safe_y:
            _draw_footer(c, width, primary_blue, grey_text)
            c.showPage()

            _draw_page_header(c, width, height, primary_blue, secondary_blue, light_blue)
            y = height - 195
            _draw_table_header(c, y, table_left, table_right, table_width, secondary_blue)
            y -= 42

        c.setFillColor(soft_blue if index % 2 == 0 else colors.white)
        c.roundRect(table_left, y - row_height, table_width, row_height, 9, fill=True, stroke=False)

        c.setStrokeColor(colors.HexColor("#D9E8FF"))
        c.roundRect(table_left, y - row_height, table_width, row_height, 9, fill=False, stroke=True)

        c.setFillColor(dark_text)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(table_left + 18, y - 22, str(index))

        c.setFillColor(primary_blue)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(table_left + 55, y - 22, "Rental / Sewaan")

        c.setFillColor(primary_blue)
        c.setFont("Helvetica-Bold", 10)
        c.drawRightString(table_right - 18, y - 22, f"RM {_format_money(amount)}")

        info_y = y - 44

        c.setFillColor(dark_text)
        c.setFont("Helvetica", 9)
        c.drawString(table_left + 55, info_y, f"Account Number: {account_number}")

        info_y -= 14
        if old_account_number != "-":
            c.drawString(table_left + 55, info_y, f"Old Account Number: {old_account_number}")
            info_y -= 14

        c.drawString(table_left + 55, info_y, f"Tenant Name: {tenant_name}")
        info_y -= 14

        c.drawString(table_left + 55, info_y, f"Registration No: {registration_no}")
        info_y -= 14

        c.drawString(table_left + 55, info_y, f"Rental Period: {start_date} - {end_date}")
        info_y -= 18

        c.setFillColor(primary_blue)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(table_left + 55, info_y, "Premise Address:")
        info_y -= 13

        c.setFillColor(colors.HexColor("#333333"))
        c.setFont("Helvetica", 9)
        for line in premise_lines:
            c.drawString(table_left + 55, info_y, line)
            info_y -= 11

        info_y -= 5

        c.setFillColor(primary_blue)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(table_left + 55, info_y, "Mailing Address:")
        info_y -= 13

        c.setFillColor(colors.HexColor("#333333"))
        c.setFont("Helvetica", 9)
        for line in mailing_lines:
            c.drawString(table_left + 55, info_y, line)
            info_y -= 11

        info_y -= 8

        c.setFillColor(dark_text)
        c.setFont("Helvetica", 9)
        c.drawString(table_left + 55, info_y, f"Outstanding Rent: RM {_format_money(outstanding_rent)}")
        info_y -= 14

        c.drawString(table_left + 55, info_y, f"Current Rental Fee: RM {_format_money(current_rent)}")
        info_y -= 14

        if float(water_charge or 0) > 0:
            c.drawString(table_left + 55, info_y, f"Water Charge: RM {_format_money(water_charge)}")
            info_y -= 14

        if float(electric_charge or 0) > 0:
            c.drawString(table_left + 55, info_y, f"Electric Charge: RM {_format_money(electric_charge)}")
            info_y -= 14

        if float(management_charge or 0) > 0:
            c.drawString(table_left + 55, info_y, f"Management Charge: RM {_format_money(management_charge)}")
            info_y -= 14

        y -= row_height + item_gap

    y -= total_gap

    total_bar_height = 42
    reminder_space = 45

    if y - total_bar_height - reminder_space < footer_safe_y:
        _draw_footer(c, width, primary_blue, grey_text)
        c.showPage()

        _draw_page_header(c, width, height, primary_blue, secondary_blue, light_blue)
        y = height - 205

    c.setFillColor(primary_blue)
    c.roundRect(table_left, y - total_bar_height, table_width, total_bar_height, 12, fill=True, stroke=False)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(table_left + 18, y - 27, "Total Paid")

    c.drawRightString(table_right - 18, y - 27, f"RM {_format_money(total_amount)}")

    y -= total_bar_height + 36

    c.setFillColor(grey_text)
    c.setFont("Helvetica", 7)
    c.drawCentredString(
        width / 2,
        y,
        "Please be informed that account balance updates may be processed on the following working day.",
    )

    _draw_footer(c, width, primary_blue, grey_text)

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer.read()


# =========================================================
# TEST SAVE PDF
# Remove this part when using inside FastAPI endpoint
# =========================================================

if __name__ == "__main__":
    api_data_1 = {
        "module": "S",
        "account_no": "S0602000081401",
        "old_account_no": "",
        "name": "KUMARI A/P MUZHY",
        "invoice_no": "",
        "start_date": "2025-08-04",
        "end_date": "2025-08-31",
        "rental_fee": "100.000000",
        "rent_alamatswn": "NO. 1",
        "rent_jalanname": "DATARAN NIAGA KARAK",
        "rent_postcode": "",
        "rent_bandarnam": "KARAK",
        "rent_negeri": "",
        "rent_pdaftaran": "740717065068",
        "alamat1": "NO. 85,",
        "alamat2": "TAMAN KARAK INDAH",
        "alamat3": "",
        "alamat4": "",
        "postcode": "28600",
        "pekan_name": "KARAK",
        "ten_negeri": "",
        "telephone": "",
        "email": "",
        "tunggakan_sewa": "400.00",
        "sewa_semasa": "",
        "tunggakan_caj_air": "",
        "caj_air_semasa": "",
        "tunggakan_caj_elektrik": "",
        "caj_elektrik_semasa": "",
        "tunggakan_caj_pengurusan": "",
        "caj_pengurusan_semasa": "",
        "jumlah": "500.00",
        "jumlah_setahun": "1100.000000",
    }

    api_data_2 = {
        "account_no": "S0602000081402",
        "old_account_no": "",
        "name": "TEST TENANT",
        "start_date": "2025-09-01",
        "end_date": "2025-09-30",
        "rental_fee": "150.000000",
        "rent_alamatswn": "NO. 2",
        "rent_jalanname": "DATARAN NIAGA KARAK",
        "rent_postcode": "",
        "rent_bandarnam": "KARAK",
        "rent_negeri": "",
        "rent_pdaftaran": "800101015555",
        "alamat1": "NO. 10",
        "alamat2": "TAMAN CONTOH",
        "alamat3": "",
        "alamat4": "",
        "postcode": "28600",
        "pekan_name": "KARAK",
        "ten_negeri": "",
        "tunggakan_sewa": "150.00",
        "tunggakan_caj_air": "0",
        "tunggakan_caj_elektrik": "0",
        "tunggakan_caj_pengurusan": "0",
        "jumlah": "150.00",
    }

    sewaan_items = [
        build_sewaan_receipt_item_from_api(api_data_1),
        build_sewaan_receipt_item_from_api(api_data_2),
    ]

    pdf_bytes = generate_sewaan_receipt_bentong(
        paid_date=datetime.datetime.now(),
        payment_method="DuitNow QR",
        order_no="ORD123456",
        bank_trx_no="BANK987654",
        sewaan_items=sewaan_items,
    )

    with open("sewaan_receipt_bentong.pdf", "wb") as f:
        f.write(pdf_bytes)

    print("PDF generated: sewaan_receipt_bentong.pdf")